In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

2025-07-05 08:48:42.578845: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-05 08:48:42.637653: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1751687322.671233    1535 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1751687322.682443    1535 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1751687322.731011    1535 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
xtr = np.array([[1.0], [2.0]], dtype=np.float32)
ytr = np.array([[300], [500]], dtype=np.float32)

In [3]:
linear_layer = Dense(units=1, activation="linear")
linear_layer.get_weights()

[]

In [4]:
a1 = linear_layer(xtr[0].reshape(1,1))
print(a1)

I0000 00:00:1751687324.796744    1535 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5563 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


tf.Tensor([[0.43387663]], shape=(1, 1), dtype=float32)


In [6]:
w, b = linear_layer.get_weights()
print(f"W= {w}, B={b}")

W= [[0.43387663]], B=[0.]


In [7]:
set_w = np.array([[200]])
set_b = np.array([100])

linear_layer.set_weights([set_w, set_b])
w1, b1 = linear_layer.get_weights()
print(f"W= {w1}, B={b1}")

W= [[200.]], B=[100.]


In [8]:
pred_tf = linear_layer(xtr)
pred_np = np.dot(xtr, set_w) + set_b

In [9]:
print(pred_tf==pred_np)

tf.Tensor(
[[ True]
 [ True]], shape=(2, 1), dtype=bool)


In [10]:
Xtr = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)
Ytr = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)

In [11]:
pos = Ytr == 1
neg = Ytr == 0

In [12]:
model = Sequential([
    Input(shape=(1,)),
    Dense(1, activation='sigmoid', name='L1')
])

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
logistic_layer = model.get_layer("L1")
w, b = logistic_layer.get_weights()
print(w, b)

[[1.6121746]] [0.]


In [15]:
set_w1 = np.array([[2]])
set_b1 = np.array([-4.5])

logistic_layer.set_weights([set_w1,set_b1])

In [16]:
log_pred_tf = logistic_layer(Xtr) 
log_pred_np = sigmoid(np.dot(Xtr, set_w1)+set_b1)

In [17]:
print(log_pred_tf)

tf.Tensor(
[[0.01098694]
 [0.07585818]
 [0.37754068]
 [0.81757444]
 [0.97068775]
 [0.9959299 ]], shape=(6, 1), dtype=float32)


In [18]:
print(log_pred_np)

tf.Tensor(
[[0.01098694]
 [0.07585818]
 [0.37754067]
 [0.81757448]
 [0.97068777]
 [0.99592986]], shape=(6, 1), dtype=float64)
