In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs
tf.autograph.set_verbosity(0)

In [3]:
def softmax(z):
    ez = np.sum(np.exp(z))
    return ez

In [16]:
## Synthetic Data
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
xtr, ytr = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

print(xtr.shape, ytr.shape)

(2000, 2) (2000,)


In [17]:
model = Sequential([
    tf.keras.layers.Input(shape=(2,)),
    Dense(25, activation="relu"),
    Dense(15, activation="relu"),
    Dense(4, activation="softmax"),
])

I0000 00:00:1751705898.651466    6892 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5563 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


In [19]:
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001)
)

model.fit(xtr, ytr, epochs=10)

Epoch 1/10


I0000 00:00:1751705975.709517    7279 service.cc:152] XLA service 0x7292940157b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1751705975.709738    7279 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 4060 Laptop GPU, Compute Capability 8.9
2025-07-05 13:59:35.754717: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1751705975.885891    7279 cuda_dnn.cc:529] Loaded cuDNN version 90701


55/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4249 

I0000 00:00:1751705976.858720    7279 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


63/63 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 1.3804
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5298 
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2632 
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1309 
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0980 
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0698 
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0733 
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0553 
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0583 
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0556 


In [20]:
pred_nonpref = model.predict(xtr)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step   


In [21]:
print(pred_nonpref[:2])

[[7.2317137e-03 4.3378179e-03 9.5846093e-01 2.9969567e-02]
 [9.9317825e-01 6.6655907e-03 1.4535245e-04 1.0741823e-05]]


In [22]:
print(np.max(pred_nonpref), np.min(pred_nonpref))

0.999997 1.0704472e-09


In [24]:
p_model = Sequential([
    tf.keras.layers.Input(shape=(2,)),
    Dense(25, activation="relu"),
    Dense(15, activation="relu"),
    Dense(4, activation="linear"),
])

p_model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.001)
)

p_model.fit(xtr, ytr, epochs=10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.9895   
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4360 
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1828 
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1102 
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0698 
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0546 
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0534 
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0447 
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0442 
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0324 


In [25]:
pred_pref = p_model.predict(xtr)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step   


In [26]:
print(pred_pref[:2])

[[ -2.9798055   -2.6046295    2.7250485   -1.1060718 ]
 [  5.366495     0.08296569  -4.962386   -10.369143  ]]


In [27]:
print(np.max(pred_pref), np.min(pred_pref))

11.379027 -16.847256


In [28]:
for i in range(5):
    print(pred_pref[i], np.argmax(pred_pref[i]))

[-2.9798055 -2.6046295  2.7250485 -1.1060718] 2
[  5.366495     0.08296569  -4.962386   -10.369143  ] 0
[ 3.6071746  0.5094009 -3.8592048 -8.22988  ] 0
[-2.2850347  2.735244  -2.5578299 -3.3402255] 1
[-1.7814293 -3.6364386  3.8092206 -5.626216 ] 2


In [29]:
## 4 Class Dataset
classes = 4
m = 100
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
std = 1.0
xtr, ytr = make_blobs(n_samples=m, centers=centers, cluster_std=std,random_state=30)

In [30]:
print(f"unique classes {np.unique(ytr)}")
print(f"class representation {ytr[:10]}")
print(f"shape of X_train: {xtr.shape}, shape of y_train: {ytr.shape}")

unique classes [0 1 2 3]
class representation [3 3 3 0 3 3 3 3 2 0]
shape of X_train: (100, 2), shape of y_train: (100,)


In [32]:
tf.random.set_seed(1234)
model = Sequential([
    tf.keras.layers.Input(shape=(2,)),
    Dense(2, activation='relu'),
    Dense(4)
])

model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.01)
)

model.fit(xtr, ytr, epochs=200)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ -1s -699857us/step - loss: 1.2584
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1495 
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0651 
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9944
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9366
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8887
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8482
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8120
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7808 
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7533
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7282
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7047 
Epoch 13/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6819
Epoch 14/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6596 
Epoch 15/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6375
Epoch 16/200
